import { Assistant, Commissioner } from "next/font/google";
import "./globals.css";
import AOSWrapper from "@/components/AOSWrapper";
import "leaflet/dist/leaflet.css";

const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["latin"],
  display: "swap",
});

const commissioner = Commissioner({
  variable: "--font-commissioner",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Data Visualization Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${assistant.variable} ${commissioner.variable}`}
    >
      <body className="bg-[#fff] font-sans antialiased">
        <AOSWrapper>
          <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
            {/* <Header /> */}
            {children}
          </div>
        </AOSWrapper>
      </body>
    </html>
  );
}
